[package]
name = "pbin-unpack"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI tool to extract and inspect PBIN files"

[[bin]]
name = "pbin-unpack"
path = "src/main.rs"

[dependencies]
pbin-core.workspace = true
